<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Anielaczki-PC" failures="0" tests="9" name="Tests.MainPageTest" time="0.042" errors="1" timestamp="2020-08-05T12:30:10 CEST" skipped="8">
  <testcase classname="Tests.MainPageTest" name="TC1" time="0.000">
    <skipped/>
  </testcase> <!-- TC1 -->
  <system-out/>
  <testcase classname="Tests.MainPageTest" name="TC7" time="0.000">
    <skipped/>
  </testcase> <!-- TC7 -->
  <system-out/>
  <testcase classname="Tests.MainPageTest" name="config" time="0.042">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Resources.Base.initializeDriver(Base.java:38)
at Tests.MainPageTest.config(MainPageTest.java:34)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:619)
at org.testng.TestRunner.beforeRun(TestRunner.java:609)
at org.testng.TestRunner.run(TestRunner.java:580)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- config -->
  <system-out/>
  <testcase classname="Tests.MainPageTest" name="TC2">
    <skipped/>
  </testcase> <!-- TC2 -->
  <system-out/>
  <testcase classname="Tests.MainPageTest" name="TC3">
    <skipped/>
  </testcase> <!-- TC3 -->
  <system-out/>
  <testcase classname="Tests.MainPageTest" name="TC6">
    <skipped/>
  </testcase> <!-- TC6 -->
  <system-out/>
  <testcase classname="Tests.MainPageTest" name="TC4">
    <skipped/>
  </testcase> <!-- TC4 -->
  <system-out/>
  <testcase classname="Tests.MainPageTest" name="TC5">
    <skipped/>
  </testcase> <!-- TC5 -->
  <system-out/>
  <testcase classname="Tests.MainPageTest" name="TC8">
    <skipped/>
  </testcase> <!-- TC8 -->
  <system-out/>
</testsuite> <!-- Tests.MainPageTest -->
